### ISSUE TITLE
TypeError in actions/vanillaforums/sso/output controller endpoint (Version 4.0.0-beta.1)

### ISSUE THREAD

**Issue by jedso** [nystudio107/craft-vanillaforums#29]
### Describe the bug
When hitting the `actions/vanillaforums/sso/output` controller endpoint (with a valid jwt query param) in the `4.0.0-beta.1` release, you get the following error:
```
TypeError
nystudio107\vanillaforums\services\Sso::getSsoData(): Argument #1 ($userId) must be of type int, string given, called in /vendor/nystudio107/craft-vanillaforums/src/services/Sso.php on line 68
```
![typerror](https://github.com/nystudio107/craft-vanillaforums/assets/26863777/0e8be79b-a746-4c32-8363-004982131dcc)

It seems like the `develop-v4` branch never received the changes originating from commit 5d44527. For example, in current `develop` branch we have:
https://github.com/nystudio107/craft-vanillaforums/blob/c41bc21721d0a109ee1cffe964aa5f2ef8fe0af3/src/services/Sso.php#L65-L68
https://github.com/nystudio107/craft-vanillaforums/blob/c41bc21721d0a109ee1cffe964aa5f2ef8fe0af3/src/services/Sso.php#L127-L137
- - -
`develop-v4` branch (and the code in the `4.0.0-beta.1` release):
https://github.com/nystudio107/craft-vanillaforums/blob/e19bda08127f1c871be709fb4620478c69668c82/src/services/Sso.php#L65-L68
https://github.com/nystudio107/craft-vanillaforums/blob/e19bda08127f1c871be709fb4620478c69668c82/src/services/Sso.php#L127-L135

Removing the $jwt argument from the `$this->getSsoData($jwt);` in the `4.0.0-beta.1` release fixes the error and the plugin works as expected.

### To reproduce
Steps to reproduce the behaviour:
1. Setup Vanilla forums + jsConnect as per docs, and use Craft 4.x + `4.0.0-beta.1` release of the plugin
1. From Vanilla forums, navigate to the login which redirects to the controller endpoint
2. Observe the error

### Expected behaviour
The endpoint does not produce an error, and redirects to a Craft login/authenticates correctly.

### Versions
- Plugin version: Version 4.0.0-beta.1
- Craft version: 4.8.0

**Comment by khalwat** [comment]
Fixed in the above commit.

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-vanillaforums": "dev-develop-v4 as 4.0.0”,
```
Then do a `composer clear-cache && composer update`
