### ISSUE TITLE
Authentication issue: "kid" invalid, unable to lookup correct key

### ISSUE THREAD

**Issue by Christopholus** [nystudio107/craft-vanillaforums#30]
### Question
Hello! We've been banging our heads against this issue for a few days now and we can't seem to get the SSO connection to work correctly. When hitting the "Test URL" button within jsConnect, we get redirected to the CraftCMS `/actions/vanillaforums/sso/output` screen with the following error:
`"kid" invalid, unable to lookup correct key`

We've tried a wide variety of patterns of URLs within jsConnect, including setting them identically to the screenshot within the documentation. It's worth noting the URL does also contain the `jwt` param.

From our reading of the documentation, there is an asynchronous request from Vanilla Forum over to the CraftCMS site, and it utilizes a session cookie to simulate a login via CraftCMS. If this is the case, would the forum and CraftCMS website have to be on identical domains? 

Our current URL structure at the moment is as such:
**Craft CMS Website: staging.clientsite.com** 
**Vanilla Forum: staging-vf.clientsite.com**

Is this the way the plugin expects the URLs to be structured? Do we need to modify our server configs to serve the forums off of `staging.clientsite.com/forums`. We are wondering if a dropped session cookie might be the issue here.

Any further direction you could provide would be a huge help for us. 

Thank you in advance!

**Comment by khalwat** [comment]
What version of Vanilla Forums & JSConnect are you using?

What version of Craft and the Vanilla Forums plugin are you using?

**Comment by Christopholus** [comment]
Hey @khalwat - thanks for the prompt reply. It turns out the issue was due to a mismatch on the SECRET_ID that was unfortunately missed during our troubleshooting steps. 

The plugin works as intended now - nothing further to resolve here. Closing it down!
